### ISSUE TITLE
Mounts are not persistent after logging out of JupyterLab instance

### ISSUE THREAD

**Issue by skoulouzis** [jsc-jupyter/jupyterlab-data-mount#1]
In a Zero2JupyterHub installation, we have configured JupyterHub DataMount Spawner. In the values  we add:

```yaml 
hub:
  args:
    - -c
    - >-
      pip install jupyterhub-datamountspawner &&
      jupyterhub -f /usr/local/etc/jupyterhub/jupyterhub_config.py
  command:
    - /bin/bash
  extraConfig:
    templates: |
      c.JupyterHub.spawner_class = 'datamountspawner.KubeSpawner'
```

2. As a user, I log in and create a new AWS mount 
3. I log out so the Jupyterlab instance is stopped 
4. I log back in and the mount is not there
